name       : python-deprecated
version    : 1.2.10
release    : 3
source     :
    - https://files.pythonhosted.org/packages/c1/2d/60b1be29720ea1a3d3146fac1a596875622ae8dcb40cf926cc4759dadfd6/Deprecated-1.2.10.tar.gz : 525ba66fb5f90b07169fdd48b6373c18f1ee12728ca277ca44567a367d9d7f74
license    : MIT
component  : programming.python
summary    : Python decorator to deprecate old python classes, functions or methods.
description: Python @deprecated decorator to deprecate old python classes, functions or methods.
rundeps    :
    - python-wrapt
build      : |
    %python3_setup
install    : |
    %python3_install
