name       : python-deprecated
version    : 1.2.6
release    : 1
source     :
    - https://files.pythonhosted.org/packages/f4/b1/3765143451fd8ba7b32c44aec8390d62fcac4ce5749c1e5ee95feaf799b7/Deprecated-1.2.6.tar.gz : a515c4cf75061552e0284d123c3066fbbe398952c87333a92b8fc3dd8e4f9cc1
license    : MIT
component  : programming.python
summary    : Python decorator to deprecate old python classes, functions or methods. 
description: |
    Python @deprecated decorator to deprecate old python classes, functions or methods. 
rundeps    :
    - python-wrapt
build      : |
    %python3_setup
install    : |
    %python3_install
