name       : python-deprecated
version    : 1.2.14
release    : 8
source     :
    - https://github.com/tantale/deprecated/archive/refs/tags/v1.2.14.tar.gz : 3309fa073e6c13a126be9fb88959a02689b15a066fa7e222a07b62325e9673a7
homepage   : https://github.com/tantale/deprecated
license    : MIT
component  : programming.python
summary    : Python decorator to deprecate old python classes, functions or methods
description: |
    Python @deprecated decorator to deprecate old python classes, functions or methods.
rundeps    :
    - python-wrapt
build      : |
    %python3_setup
install    : |
    %python3_install
